language: cpp
sudo: false
os: osx

############
# Main rules
############
before-script:
      - brew tap DGtal-team/DGtal
jobs:
  include:
    - stage: Checking the formula
      script: brew audit dgtal
    - stage: Checking the build
      script: brew install dgtal ; brew test dgtal
